# Generated by Django 6.1 on 2026-08-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='applied', max_length=30),
        ),
    ]
