# Generated by Django 6.1 on 2026-08-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0005_desiredprofile_educationdetail_employmenthistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='recruiter_actions',
            field=models.IntegerField(default=294),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='search_appearances',
            field=models.IntegerField(default=7868),
        ),
    ]
