# Generated by Django 6.1 on 2026-08-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0007_alter_userprofile_recruiter_actions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
