# Generated by Django 6.1 on 2026-08-26 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0009_userprofile_email_notifications_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(max_length=255)),
                ('salary', models.CharField(max_length=100)),
                ('joining_date', models.DateField()),
                ('message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer_letter', to='screening.application')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('degree', 'Degree / Education Certificate'), ('pan', 'PAN Card'), ('aadhaar', 'Aadhaar Card'), ('photo', 'Passport-size Photo'), ('relieving', 'Previous Employment / Relieving Letter')], max_length=20)),
                ('file', models.FileField(upload_to='candidate_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='screening.application')),
            ],
            options={
                'unique_together': {('application', 'doc_type')},
            },
        ),
    ]
