# Generated by Django 6.1 on 2026-08-26 10:10

from django.db import migrations, models


def mark_existing_offers_as_sent(apps, schema_editor):
    # Every OfferLetter created before this migration was sent immediately
    # on save (there was no draft/preview step yet) - so they should keep
    # showing up as sent, not silently turn into hidden drafts.
    OfferLetter = apps.get_model('screening', 'OfferLetter')
    OfferLetter.objects.filter(sent_at__isnull=False).update(is_sent=True)


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0011_offerletter_letter_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerletter',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='reporting_manager',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='offerletter',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(mark_existing_offers_as_sent, migrations.RunPython.noop),
    ]
