# Generated by Django 6.1 on 2026-08-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0012_offerletter_preview_flow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerletter',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offerletter',
            name='letter_file',
            field=models.FileField(default='', upload_to='offer_letters/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offerletter',
            name='role_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='offerletter',
            name='salary',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]