# Generated by Django 6.1 on 2026-08-26 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0013_alter_offerletter_joining_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candidatedocument',
            unique_together=set(),
        ),
    ]
